// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTXMe13YuMbUI2d35ywZE78Uwd84KQFko',
    appId: '1:780475069816:web:86e745b31fa6b36e41048d',
    messagingSenderId: '780475069816',
    projectId: 'qlees-bd6a4',
    authDomain: 'qlees-bd6a4.firebaseapp.com',
    storageBucket: 'qlees-bd6a4.firebasestorage.app',
    measurementId: 'G-YJP65R4GKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7c8FXCBGqAdxCXxjGfHbqSi874aZ9gVQ',
    appId: '1:780475069816:android:abc76a893a0b7dad41048d',
    messagingSenderId: '780475069816',
    projectId: 'qlees-bd6a4',
    storageBucket: 'qlees-bd6a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPwD_gP79tJgLtwjK2_AqZB8jSxeHNBoY',
    appId: '1:780475069816:ios:c8bc229b87820a5241048d',
    messagingSenderId: '780475069816',
    projectId: 'qlees-bd6a4',
    storageBucket: 'qlees-bd6a4.firebasestorage.app',
    androidClientId: '780475069816-63glqgd3i1evgt5eumu2d7212v50nlnd.apps.googleusercontent.com',
    iosClientId: '780475069816-so29n6ig7m1ggud7us4jkchjkn8u3cp6.apps.googleusercontent.com',
    iosBundleId: 'com.example.qless',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPwD_gP79tJgLtwjK2_AqZB8jSxeHNBoY',
    appId: '1:780475069816:ios:c8bc229b87820a5241048d',
    messagingSenderId: '780475069816',
    projectId: 'qlees-bd6a4',
    storageBucket: 'qlees-bd6a4.firebasestorage.app',
    androidClientId: '780475069816-63glqgd3i1evgt5eumu2d7212v50nlnd.apps.googleusercontent.com',
    iosClientId: '780475069816-so29n6ig7m1ggud7us4jkchjkn8u3cp6.apps.googleusercontent.com',
    iosBundleId: 'com.example.qless',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNIBjfWlaX9TIu6jxv-YS5u9Pt3HPu9B0',
    appId: '1:780475069816:web:974a0629a1bd668e41048d',
    messagingSenderId: '780475069816',
    projectId: 'qlees-bd6a4',
    authDomain: 'qlees-bd6a4.firebaseapp.com',
    storageBucket: 'qlees-bd6a4.firebasestorage.app',
    measurementId: 'G-KRV0T7CP8G',
  );
}
