// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLHeyYmvLol1wh2-7ZuWBaJgBAZijnroU',
    appId: '1:802774746484:android:07acc455884ea8442e1821',
    messagingSenderId: '802774746484',
    projectId: 'q-less-93d8f',
    storageBucket: 'q-less-93d8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSzHrrqoH1ajHqJ3GnmX6gSKEMSpyQ9f0',
    appId: '1:802774746484:ios:9650d546aeea94632e1821',
    messagingSenderId: '802774746484',
    projectId: 'q-less-93d8f',
    storageBucket: 'q-less-93d8f.firebasestorage.app',
    iosClientId: '802774746484-o96v3u3o1vj7vu77aidqkm11h6372o75.apps.googleusercontent.com',
    iosBundleId: 'com.example.qLes',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHD3zXitjr3O4Vznqfj-xCMGURxdpm990',
    appId: '1:802774746484:web:84506e951e568a182e1821',
    messagingSenderId: '802774746484',
    projectId: 'q-less-93d8f',
    authDomain: 'q-less-93d8f.firebaseapp.com',
    storageBucket: 'q-less-93d8f.firebasestorage.app',
    measurementId: 'G-Z9390DFQB7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSzHrrqoH1ajHqJ3GnmX6gSKEMSpyQ9f0',
    appId: '1:802774746484:ios:9650d546aeea94632e1821',
    messagingSenderId: '802774746484',
    projectId: 'q-less-93d8f',
    storageBucket: 'q-less-93d8f.firebasestorage.app',
    iosClientId: '802774746484-o96v3u3o1vj7vu77aidqkm11h6372o75.apps.googleusercontent.com',
    iosBundleId: 'com.example.qLes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0d-lTY3Hi6y6FpKvxGEtkuzoV0r52Qmw',
    appId: '1:802774746484:web:73167e3d6531d0392e1821',
    messagingSenderId: '802774746484',
    projectId: 'q-less-93d8f',
    authDomain: 'q-less-93d8f.firebaseapp.com',
    storageBucket: 'q-less-93d8f.firebasestorage.app',
    measurementId: 'G-QY63X254R8',
  );

}